src/lib.rs, src/tokenizer.rs
The is a bug in string escaping code. 
Reproduction:
```rust
fn main() {
use sqlformat::*;
let res = format("''some text ending with escaped quote''", &QueryParams::None, FormatOptions::default());
println!("{res}");
}
```
prints:
```
' some text ending with escaped quote ' ''
```
but should print:
```
'some text ending with escaped quote'''
```
It's a small bug in `tokenizer::take_till_escaping`, which I fixed and added a test to cover this case.
=> Fix string escaping

src/lib.rs, src/tokenizer.rs
Fixes #20. 
The output from the example in that issue is now
```sql
CREATE
OR REPLACE FUNCTION generate_ulid() RETURNS uuid AS
$$
SELECT
(
lpad(
to_hex(
floor(
extract(
epoch
FROM
clock_timestamp()
) * 1000
) :: bigint
),
12,
'0'
) || encode(gen_random_bytes(10), 'hex')
) :: uuid;
$$
LANGUAGE SQL;
```
I think the `::` should not have spaces around it but that can wait for another PR. For now, this allows Postgres to parse it properly.
=> treat $$ as a reserved token

src/lib.rs, src/tokenizer.rs
1e16 and 1e+16 are both valid.
Attempts to fix https://github.com/shssoichiro/sqlformat-rs/issues/22
=> Allow scientific notation without + or - as these are optional.

src/lib.rs, src/tokenizer.rs
This builds on #29.
Format `DECLARE` and `BEGIN` on their own lines so that Postgres functions look better.
Reference: https://www.postgresql.org/docs/current/plpgsql-structure.html
=> Format "begin" and "declare" for plpgsql

Cargo.toml, src/lib.rs, src/params.rs, src/tokenizer.rs
- I've made "$" a valid identifier in get_ident_named_placeholder_token().
- Added some tests mixing indexed and named parameters.
- Adjusting the parameter precedence based on the initial QueryParams provided. (Named vs Indexed).
- The first commit https://github.com/shssoichiro/sqlformat-rs/commit/766c92316d77ba18f66c65b57b52838fadf67d03 was sufficient to get to where I wanted to get, the rest just addresses mixed parameter types which might not actually be a real issue anyway...
Attempts to fix https://github.com/shssoichiro/sqlformat-rs/issues/18
I don't have a Rust background so there may be better ways of doing this. 
Happy to adjust as necessary or throw out the lot as it may be.
Thanks.
=> Allow alphanumeric characters in SQLLite style parameters.

Cargo.toml, src/formatter.rs
Itertools was only be used for the .join() method.
=> Remove itertools as a dependency

src/formatter.rs, src/lib.rs
input text:
```sql
-- 创建一个外部表，存储销售数据
CREATE EXTERNAL TABLE IF NOT EXISTS sales_data (
-- 唯一标识订单ID
order_id BIGINT COMMENT 'Unique identifier for the order',
-- 客户ID
customer_id BIGINT COMMENT 'Unique identifier for the customer'
)
COMMENT 'Sales data table for storing transaction records';
-- 按销售日期和城市进行分区
PARTITIONED BY (
sale_year STRING COMMENT 'Year of the sale',
sale_month STRING COMMENT 'Month of the sale'
)
-- 设置数据存储位置
LOCATION '/user/hive/warehouse/sales_data'
-- 使用 ORC 存储格式
STORED AS ORC
-- 设置表的行格式
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
-- 设置表属性
TBLPROPERTIES (
'orc.compress' = 'SNAPPY',          -- 使用SNAPPY压缩
'transactional' = 'true',           -- 启用事务支持
'orc.create.index' = 'true',        -- 创建索引
'skip.header.line.count' = '1',     -- 跳过CSV文件的第一行 …
```
=> fix: fix the issue of misaligned comments after formatting

src/lib.rs, src/tokenizer.rs
Closes https://github.com/shssoichiro/sqlformat-rs/issues/39
=> fix: Escaped strings formatted incorrectly

src/lib.rs, src/tokenizer.rs
Closes https://github.com/shssoichiro/sqlformat-rs/issues/27
=> fix: REFERENCES xyz ON UPDATE .. causes formatter to treat the remaining as an UPDATE statement

Cargo.toml, src/formatter.rs, src/lib.rs
fix: https://github.com/shssoichiro/sqlformat-rs/issues/15
=> fix: Possible to provide an escape hatch for expressions

benches/bench.rs, src/formatter.rs, src/indentation.rs, src/lib.rs
fix: https://github.com/shssoichiro/sqlformat-rs/issues/33
=> fix: Ignore keywords for uppercase=True

src/lib.rs, src/tokenizer.rs
Add a combinator of any group of operators. In needs to be before parsed a bit earlier before placeholders to not split on `?`. I split the operators to 2-5 and moved it earlier and left the single characters at the end.
=> allow_any_combination_of_operators

src/formatter.rs, src/tokenizer.rs
I can't guarantee that this is 100% correct solution but all the tests are green.
The best part is in the bench and I think the code is more readable because it fits on the screen:
I only split 2 functions - the most popular one where select is and the huge one
=> optimize matching

src/lib.rs, src/tokenizer.rs
https://clickhouse.com/docs/en/sql-reference/statements/select/join
https://duckdb.org/docs/sql/query_syntax/from.html
=> support ClickHouse/DuckDB join variants

Cargo.toml, src/tokenizer.rs
I want to be clear, just because I did this, there is no pressure to adopt it. I did this more out of procrastination than anything and then turned into a personal challenge (as I explain later).  If this PR is not wanted, I can split out any desired clean up or performance improvements independent of Winnow and submit that.
From [v0.1.1 release](https://github.com/shssoichiro/sqlformat-rs/blob/master/CHANGELOG.md#version-012)
> Rewrite the parser in nom, providing significant performance improvements across the board
Since the use of `nom` was for performance reasons, I kept a careful eye on performance.  Each commit lists the performance compared to the previous commit.  There is some noise in my runs, so we can't read too much into small changes.
I was surprised to find that switching …
=> Port to Winnow

Cargo.toml, src/formatter.rs, src/inline_block.rs, src/lib.rs
It allows to have a more compact formatting of SELECT, probably a similar logic could be used for other arguments as well.
=> More formatting options

src/formatter.rs, src/inline_block.rs, src/lib.rs
=> Uniform the behaviour of block and top-level span options

src/formatter.rs, src/indentation.rs, src/lib.rs, src/tokenizer.rs
Another bunch of fixes in the logic (hopefully), plus switching WITH to the top level worlds (no indent).
=> Fix span computation

Cargo.toml, src/tokenizer.rs
```
Running benches/bench.rs (target/release/deps/bench-15db45057a99e718)
simple query            time:   [3.3353 µs 3.3459 µs 3.3588 µs]
change: [+1.7491% +2.9980% +4.2079%] (p = 0.00 < 0.05)
Performance has regressed.
complex query           time:   [16.054 µs 16.086 µs 16.114 µs]
change: [-10.142% -9.1919% -8.2558%] (p = 0.00 < 0.05)
Performance has improved.
named params            time:   [6.1227 µs 6.1298 µs 6.1380 µs]
change: [-1.6477% -1.2976% -0.9061%] (p = 0.00 < 0.05)
Change within noise threshold.
Found 3 outliers among 100 measurements (3.00%)
2 (2.00%) high mild
1 (1.00%) high severe
explicit indexed params time:   [6.0797 µs 6.0869 µs 6.0943 µs]
change: [-8.1424% -7.8433% -7.5629%] (p = 0.00 < 0.05)
Performance has improved.
Found 4 outliers among 100 measurements (4.00%)
3 …
```
=> chore: Upgrade to Winnow 0.7.0

src/formatter.rs, src/indentation.rs, src/inline_block.rs, src/lib.rs, src/tokenizer.rs
Fix again the span computation, make so the compact representation does not behave weirdly when it needs to go columnar in subqueries.
Now it is really getting closer to ideal if somebody wants a compact representation.
Yet to be done:
=> Improve the inline/columnar combination

src/formatter.rs, src/indentation.rs, src/lib.rs
This way WITH with nested queries are formatted correctly
=> Keep the previous tokens per-block

src/formatter.rs, src/lib.rs
In the case of a WITH statement fitting a single line the current formatter doesn't add the space needed.
=> Fix formatting WITH as a single line

.github/workflows/sqlformat.yml, src/formatter.rs, src/lib.rs, src/tokenizer.rs
`CASE` `END` and `(` and `)` have different requirements regarding the whitespace
=> Format inline CASE <expression> WHEN correctly
